### ISSUE TITLE
Skipping upload because path function returned no path.

### ISSUE THREAD

**Issue by siddharthalodha** [Zahlii/colab-tf-utils#4]
I am getting this error many times. Sometimes, after 10-12 epochs, it begins uploading but sometimes it doesn't upload anything. Any idea ?

**Comment by Zahlii** [comment]
Hi, this is actually expected behavior. As long as the path function returns "None" or any "False" value, the intermediate steps are not saved. This is done to speed up the initial epochs where the accuracy is low and the loss is high. The function in the README file.e.g only saved checkpoints once the validation accuracy is higher than 80%. I hope this clarifies your issue :)

**Comment by siddharthalodha** [comment]
Ok Thanks. Got it. My network typically reaches 80% around epoch 10-12.
